version: 2.1

jobs:
  rpmbuilder:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "Building all PR scoped packages"
          command: "scripts/handler.sh"
      - store_artifacts:
          path: files/
workflows:
  rpmbuilder-workflow:
    jobs:
      - rpmbuilder
