version: 2.1

jobs:
  rpmbuilder:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: "Building image with docker-compose"
          command: "docker build -t mockzor ."
      - run:
          name: "Starting privileged mock container"
          command: "docker run -it -d --name mock -v /home/circleci/project:/project --cap-add=SYS_ADMIN --security-opt apparmor:unconfined mockzor"
      - run:
          name: "Listing running containers"
          command: "docker ps -a"
      - run:
          name: "Generating SRPM with rpmbuilder"
          command: "docker exec -ti mock /project/scripts/buildsrpm.sh puppet.spec"
      - run:
          name: "Running mock againt rocky+epel 8"
          command: "docker exec -ti mock /project/scripts/runmock.sh rocky+epel-8-x86_64 puppet-6.19.0-1.fc34.src.rpm"
      - run:
          name: "Copying over RPMs"
          command: "docker exec -ti mock /project/scripts/copyrpms.sh"
      - store_artifacts:
          path: /project/output/*
workflows:
  rpmbuilder-workflow:
    jobs:
      - rpmbuilder
